# Generated by Django 5.0.2 on 2024-03-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('post_id', models.AutoField(db_column='post_id', primary_key=True, serialize=False)),
                ('caption', models.CharField(db_column='caption', default=None, max_length=256)),
                ('post_pic', models.ImageField(upload_to='Images/PostPic')),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='Registration.userprofile')),
            ],
            options={
                'db_table': 'ss_post',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(db_column='like_id', primary_key=True, serialize=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('follower', models.ForeignKey(db_column='follower', on_delete=django.db.models.deletion.CASCADE, to='Registration.userprofile')),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='Posts.userpost')),
            ],
            options={
                'db_table': 'ec_like',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(db_column='comment_id', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', default=None, max_length=256)),
                ('is_notified', models.BooleanField(default=False)),
                ('follower', models.ForeignKey(db_column='follower', on_delete=django.db.models.deletion.CASCADE, to='Registration.userprofile')),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='Posts.userpost')),
            ],
            options={
                'db_table': 'ec_comment',
            },
        ),
    ]
