# Generated by Django 5.0.2 on 2024-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_comments_created_at_comments_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
