# Generated by Django 5.0.2 on 2024-04-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_comments_updated_at_alter_like_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='is_deleted',
        ),
    ]
