# Generated by Django 5.0.2 on 2024-04-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_remove_comments_is_deleted_remove_like_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='caption',
            field=models.CharField(db_column='caption', default=None, max_length=256, null=True),
        ),
    ]
