# Generated by Django 5.0.2 on 2024-04-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_userpost_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_count',
            field=models.IntegerField(db_column='comment_count', default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(db_column='like_count', default=0),
        ),
    ]
