# Generated by Django 5.0.2 on 2024-04-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_comments_comment_count_like_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_count',
        ),
        migrations.AddField(
            model_name='userpost',
            name='comment_count',
            field=models.IntegerField(db_column='comment_count', default=0),
        ),
        migrations.AddField(
            model_name='userpost',
            name='like_count',
            field=models.IntegerField(db_column='like_count', default=0),
        ),
    ]
