# Generated by Django 5.0.2 on 2024-04-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_remove_comments_comment_count_remove_like_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_pic',
            field=models.FileField(upload_to='Images/PostPic'),
        ),
    ]
