# Generated by Django 5.0.2 on 2024-03-30 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('connection_id', models.AutoField(db_column='connection_id', primary_key=True, serialize=False)),
                ('request_status', models.BooleanField(default=False)),
                ('is_requested', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('requested_user', models.ForeignKey(db_column='requested_user', on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to='Registration.userprofile')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='uc_user', to='Registration.userprofile')),
            ],
            options={
                'db_table': 'ss_user_connection',
            },
        ),
    ]
