# Generated by Django 5.0.2 on 2024-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0002_userconnection_created_at_userconnection_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
