# Generated by Django 5.0.2 on 2024-03-30 06:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', default='', max_length=256)),
                ('password', models.CharField(db_column='password', default='', max_length=256)),
                ('email', models.CharField(db_column='email', default='', max_length=256)),
                ('date_of_birth', models.DateField()),
                ('profile_pic', models.ImageField(db_column='profile_pic', default='', upload_to='Images/ProfilePic')),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False)),
                ('is_private', models.BooleanField(db_column='is_private', default=False)),
                ('follower_count', models.IntegerField(db_column='follower_count', default=0)),
                ('following_count', models.IntegerField(db_column='following_count', default=0)),
                ('bio', models.CharField(db_column='bio', default='', max_length=256)),
            ],
            options={
                'db_table': 'ss_user_profile',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserProfile',
            fields=[
                ('user_id', models.IntegerField(blank=True, db_column='user_id', db_index=True)),
                ('username', models.CharField(db_column='username', default='', max_length=256)),
                ('password', models.CharField(db_column='password', default='', max_length=256)),
                ('email', models.CharField(db_column='email', default='', max_length=256)),
                ('date_of_birth', models.DateField()),
                ('profile_pic', models.TextField(db_column='profile_pic', default='', max_length=100)),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False)),
                ('is_private', models.BooleanField(db_column='is_private', default=False)),
                ('follower_count', models.IntegerField(db_column='follower_count', default=0)),
                ('following_count', models.IntegerField(db_column='following_count', default=0)),
                ('bio', models.CharField(db_column='bio', default='', max_length=256)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user profile',
                'verbose_name_plural': 'historical user profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
