# Generated by Django 5.0.2 on 2024-03-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_alter_historicaluserprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='profile_pic',
            field=models.TextField(db_column='profile_pic', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(db_column='profile_pic', default=None, null=True, upload_to='Images/ProfilePic'),
        ),
    ]
