# Generated by Django 5.0.2 on 2024-04-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_alter_historicaluserprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_deleted',
        ),
    ]
