# Generated by Django 5.0.2 on 2024-03-30 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('useractivity_id', models.AutoField(db_column='useractivity_id', primary_key=True, serialize=False)),
                ('active_time', models.IntegerField(db_column='active_time', default=0)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='Registration.userprofile')),
            ],
            options={
                'db_table': 'ec_user_activity',
            },
        ),
    ]
