# Generated by Django 5.0.2 on 2024-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_alter_useractivity_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
