# Generated by Django 5.0.2 on 2024-04-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_alter_useractivity_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='is_deleted',
        ),
    ]
